### ISSUE TITLE
which version of arduinoFFT ?

### ISSUE THREAD

**Issue by dalemcbeath** [blaz-r/ESP32-music-beat-sync#1]
Hi, blaze-r

I just tried your code, and get lots of errors relating to arduinoFFT.  I loaded that library from the Arduino IDE, and there was only one by that name, made by Enrique Condes.

It mostly seems to be capitalization issues, but there are also functions needing more/fewer items.  Looks like they might have updated the library?  I tried a few older versions, but all get errors.  Or I may simply be missing something basic.  

Thanks for your time, looking forward to trying your code.

dm

**Comment by blaz-r** [comment]
As stated in description, you will need to use library from "develop" branch, since that one has float support and some additional features. So after cloning ArduinoFFT, you'll need to checkout to develop branch to get correct files.
Hope that helps 😃

**Comment by dalemcbeath** [comment]
thank you, I missed that remark in the readme.

**Comment by Tycho-S** [comment]
Oh oops I just logged a similar ticket. Didn't see this one as it was closed.

The latest devel branch doesn't work but I guess I need to find one from around 2022? You don't have a commit ID by any chance?
